// Generated by https://quicktype.io

export interface IServicio {
    id:          number;
    titulo:      string;
    categoria:   string;
    descripcion: string;
    imagen:      string;
    tecnologias: string[];
}